### ISSUE TITLE
image from the documentation are still pointing to my personnal fork

### ISSUE THREAD

**Issue by 12rambau** [openforis/bfastspatial#4]
@dfguerrerom a while ago you suggested me to delete my fork of the bfast documentation which I gladly did but now the BFAST monitor documentation don't have images anymore as the links have not been changed in the rst file.

**Comment by dfguerrerom** [comment]
thanks for letting me know. fixed with ebe938039e0391b4e2b8709d5a6ad79eca21a0f7
